name = "WeenieCraft 1.21.7"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6f62abb8bc2a9debf0ca60ce30f3538264790e3383e020fb0156aac49767a85"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
